---
- name: Create ambot system group
  group:
    name: "{{ ambot_system_group }}"
    state: present
    system: true
  when: ambot_system_group != "root"

- name: Create ambot system user
  user:
    name: "{{ ambot_system_user }}"
    groups: "{{ ambot_system_group }}"
    append: true
    shell: /usr/sbin/nologin
    system: true
    createhome: true
    home: "{{ ambot_db_dir }}"
  when: ambot_system_user != "root"
